//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiAssistAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custody
    {
        public int studentId { get; set; }
        public int staffId { get; set; }
        public System.DateTime custodyStartTime { get; set; }
        public Nullable<System.DateTime> custodyEndTime { get; set; }
        public string custodyType { get; set; }
        public Nullable<System.DateTime> TimeAlertRaised { get; set; }
        public Nullable<System.DateTime> TimeAlertCancelled { get; set; }
    
        public virtual CustodyType CustodyType1 { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Student Student { get; set; }
    }
}
