//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiAssistAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkiAssistDBEntities : DbContext
    {
        public SkiAssistDBEntities()
            : base("name=SkiAssistDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Custody> Custody { get; set; }
        public virtual DbSet<CustodyType> CustodyType { get; set; }
        public virtual DbSet<Diet> Diet { get; set; }
        public virtual DbSet<Guardian> Guardian { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentGuardian> StudentGuardian { get; set; }
        public virtual DbSet<StudentSkill> StudentSkill { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<MedicalConditions> MedicalConditions { get; set; }
        public virtual DbSet<Token> Token { get; set; }
    }
}
