//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiAssistAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSkill
    {
        public int studentId { get; set; }
        public string skillTitle { get; set; }
        public Nullable<byte> isPassed { get; set; }
        public string studentskillNotes { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual Student Student { get; set; }
    }
}
